// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAeadZ6AAdwGOUzvjo3Gu56m6umTqOek2Y',
//     appId: '1:750553767736:web:010181037a61ac41e0abcd',
//     messagingSenderId: '750553767736',
//     projectId: 'task1-9734d',
//     authDomain: 'task1-9734d.firebaseapp.com',
//     storageBucket: 'task1-9734d.appspot.com',
//     measurementId: 'G-0JWKCQYXGX',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDAYTmMCfxf_hFMWvPrHVcRqsURhL1bMr8',
//     appId: '1:750553767736:android:13bcc347bb23e2efe0abcd',
//     messagingSenderId: '750553767736',
//     projectId: 'task1-9734d',
//     storageBucket: 'task1-9734d.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBHOhdqPQ25BJtKYfzI1EQvdMQC862Ldfg',
//     appId: '1:750553767736:ios:b7505b684267adeee0abcd',
//     messagingSenderId: '750553767736',
//     projectId: 'task1-9734d',
//     storageBucket: 'task1-9734d.appspot.com',
//     iosBundleId: 'com.example.task1',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBHOhdqPQ25BJtKYfzI1EQvdMQC862Ldfg',
//     appId: '1:750553767736:ios:b7505b684267adeee0abcd',
//     messagingSenderId: '750553767736',
//     projectId: 'task1-9734d',
//     storageBucket: 'task1-9734d.appspot.com',
//     iosBundleId: 'com.example.task1',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAeadZ6AAdwGOUzvjo3Gu56m6umTqOek2Y',
//     appId: '1:750553767736:web:8e036ef2daffe856e0abcd',
//     messagingSenderId: '750553767736',
//     projectId: 'task1-9734d',
//     authDomain: 'task1-9734d.firebaseapp.com',
//     storageBucket: 'task1-9734d.appspot.com',
//     measurementId: 'G-VXW2QJDZ72',
//   );
// }
